version: '3.8'

services:
  web:
    build: ./app
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
    volumes:
      - ./logs:/app/logs
    networks:
      - app_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network
    restart: on-failure

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
